import json, pprint, fnmatch, re

# was attributed to
agent1 = []
entity1 = []
with open('wasAttributedTo.json', encoding='utf-8') as file:
   data = file.readlines()
   for d in data:
      d = json.loads(d)
      agent1.append(d['p']['nodes'][0])
      entity1.append(d['p']['nodes'][1])

# was generated by
entity2 = []
activity1 = []
with open('wasGeneratedBy.json', encoding='utf-8') as file:
   data = file.readlines()
   for d in data:
      d = json.loads(d)
      entity2.append(d['p']['nodes'][0])
      activity1.append(d['p']['nodes'][1])

# was associated with (activity agent)
activity2 = []
agent2 = []
with open('wasAssociatedWith.json', encoding='utf-8') as file:
   data = file.readlines()
   for d in data:
      d = json.loads(d)
      activity2.append(d['p']['nodes'][0])
      agent2.append(d['p']['nodes'][1])

#pair(index1, index2)
pairs1 = []
for index1, e1 in enumerate(entity1):
   for index2, e2 in enumerate(entity2):
      if e1['id'] == e2['id']:
         #print(index1, index2)
         #print(entity1[index1], entity2[index2])
         #if entity1[index1] == entity2[index2]:
         #   print(True)
         pairs1.append([agent1[index1], entity1[index1], activity1[index2]])
         #pairs1.append([index1, index2])

pairs2 = []
for index1, a1 in enumerate(activity1):
   for index2, a2 in enumerate(activity2):
      if a1['id'] == a2['id']:
         #print(index1, index2)
         #if activity1[index1] == activity2[index2]:
         #   print(True)
         pairs2.append([entity2[index1], activity1[index1], agent2[index2]])
         #pairs2.append([index1, index2])


#print(pairs1, pairs2)

result = []
join_result = []
for p1 in pairs1:
   #print(p1[0]['id'])
   for p2 in pairs2:
      #print(p2[2]['id'])
      if p1[0]['id'] == p2[2]['id'] and p1[1]['id'] == p2[0]['id'] and p1[2]['id'] == p2[1]['id']: # agent compare
       #  print(p1,p2)
         result = [p1[0]['properties']['name'],p1[0]['properties']['affiliation'], #Agent
                   p1[2]['properties']['name'],p1[2]['properties']['date'],p1[1]['properties']['name'], #Entity
                   p1[1]['properties']['dataType'],p1[1]['properties']['price'],p1[1]['properties']['device']] #Activity
         delimiter='-'
         join_result.append(delimiter.join(result))
#for i in range(len(join_result)):
#    print(join_result[i])
      # p1 agent entity activity
      # p2 entity activity agent
#for i in range(len(p1_list)):
#    print(p1_list[0]['properties']['name'],"-",p1_list[1]['properties']['name'],"-",p1_list[2]['properties']['name'])      

#searchTerm = '*AI스피커*'
#print(fnmatch.filter(join_result, searchTerm))
#print(re.findall(searchTerm, join_result))

'''
{'type': 'node', 'id': '0', 'labels': ['Entity'], 'properties': {'price': '1066274', 'dataType': '음성데이터', 'name': 'data_995', 'device': 'AI스피커'}}
{'type': 'node', 'id': '65', 'labels': ['Entity'], 'properties': {'price': '1566401', 'dataType': '건강데이터', 'name': 'data_414', 'device': '스마트워치'}}
'''